import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Printing Services in Tanuku | Flex, Vinyl, LED Sign Boards | Sri Teja Flex",
  description: "Complete range of printing services in Tanuku, West Godavari. Flex printing, vinyl printing, LED sign boards, foam board printing, visiting cards, flute boards, one way vision. Best prices and quality.",
  keywords: [
    "printing services near me",
    "printing services Tanuku",
    "printing services West Godavari",
    "printing services Andhra Pradesh",
    "flex printing near me",
    "flex printing Tanuku",
    "flex printing West Godavari",
    "flex printing Andhra Pradesh",
    "flex banner printing",
    "flex banner printing near me",
    "outdoor flex printing",
    "shop flex printing",
    "political flex printing",
    "event flex printing",
    "festival flex printing",
    "large flex printing",
    "custom flex banners",
    "advertising flex printing",
    "hoarding flex printing",
    "business flex banners",
    "cheap flex printing",
    "high quality flex printing",
    "durable flex banners",
    "flex printing shop",
    "flex printing company",
    "flex banner makers",
    "flex board printing",
    "digital flex printing",
    "flute board printing",
    "flute board printing near me",
    "flute board printing Tanuku",
    "flute board sign boards",
    "outdoor flute boards",
    "flute board advertising boards",
    "flute board printing services",
    "plastic flute board printing",
    "real estate flute boards",
    "political flute boards",
    "school flute boards",
    "hospital flute boards",
    "campaign flute boards",
    "promotion flute boards",
    "custom flute boards",
    "cheap flute board printing",
    "durable flute boards",
    "lightweight advertising boards",
    "printed flute boards",
    "sign flute boards",
    "corrugated flute boards",
    "advertisement flute boards",
    "vinyl printing services",
    "vinyl printing near me",
    "vinyl printing Tanuku",
    "vinyl sticker printing",
    "vinyl banner printing",
    "shop vinyl printing",
    "wall vinyl printing",
    "vinyl branding printing",
    "custom vinyl graphics",
    "vinyl advertising prints",
    "vinyl poster printing",
    "vinyl sign printing",
    "vinyl wall stickers printing",
    "vinyl glass stickers printing",
    "vehicle vinyl stickers",
    "vinyl decal printing",
    "custom vinyl stickers",
    "shop window vinyl printing",
    "advertising vinyl stickers",
    "commercial vinyl printing",
    "one way vision printing",
    "one way vision printing near me",
    "one way vision stickers",
    "window branding printing",
    "glass branding stickers",
    "shop window advertising",
    "glass sticker printing",
    "window advertising stickers",
    "one way vision glass stickers",
    "custom window stickers",
    "shop window branding",
    "window display printing",
    "commercial window branding",
    "led sign board makers",
    "led sign board printing",
    "led shop board",
    "led sign boards near me",
    "custom led sign boards",
    "led display boards",
    "led advertising boards",
    "illuminated sign boards",
    "led board makers",
    "digital led boards",
    "shop led boards",
    "led advertising signage",
    "led business boards",
    "led sign board manufacturers",
    "led sign board Tanuku",
    "visiting card printing",
    "visiting card printing near me",
    "visiting card printing Tanuku",
    "business card printing",
    "custom visiting cards",
    "premium visiting card printing",
    "professional visiting cards",
    "fast visiting card printing",
    "affordable visiting cards",
    "digital visiting card printing",
    "creative visiting cards",
    "modern visiting card designs",
    "corporate visiting cards",
    "shop visiting cards",
    "company visiting cards",
    "cheap visiting cards",
    "foam board printing",
    "foam board printing near me",
    "foam board printing Tanuku",
    "foam board sign printing",
    "custom foam board printing",
    "advertising foam boards",
    "exhibition foam boards",
    "foam display boards",
    "foam signage boards",
    "foam board posters",
    "indoor foam boards",
    "foam board printing services",
    "sign board printing",
    "sign board printing near me",
    "sign board printing Tanuku",
    "custom sign boards",
    "outdoor sign boards",
    "shop sign boards",
    "business sign boards",
    "advertising sign boards",
    "sign board manufacturers",
    "commercial sign boards",
    "company sign boards",
    "professional sign boards",
    "advertising board printing",
    "outdoor advertising boards",
    "business advertising boards",
    "marketing banner printing",
    "promotion banner printing",
    "campaign banner printing",
    "event promotion banners",
    "shop advertising banners",
    "commercial banner printing",
    "political banner printing",
    "political flex printing",
    "election banner printing",
    "campaign flex banners",
    "political advertising boards",
    "election promotion banners",
    "political poster printing",
    "school banner printing",
    "school notice board printing",
    "educational signage printing",
    "school event banners",
    "college banner printing",
    "hospital sign boards",
    "medical signage printing",
    "hospital direction boards",
    "clinic sign board printing",
    "medical banner printing",
    "pesticide advertising boards",
    "fertilizer company boards",
    "agriculture promotion boards",
    "agri product banner printing",
    "banner printing near me",
    "banner printing Tanuku",
    "banner printing West Godavari",
    "custom banner printing near me",
    "large banner printing near me",
    "poster printing near me",
    "business printing near me",
    "shop board printing near me",
    "cheap flex printing near me",
    "fast banner printing near me",
    "outdoor banner printing near me",
    "indoor banner printing near me",
    "commercial printing near me",
    "flex board printing near me",
    "custom sign boards near me",
    "professional printing near me",
    "graphic printing near me",
    "best flex printing services in Tanuku",
    "affordable flex printing in Tanuku",
    "professional banner printing services",
    "custom sign board printing services",
    "cheap banner printing for shops",
    "outdoor advertising board printing services",
    "high quality vinyl printing services",
    "led sign board makers for shops",
    "professional printing services for businesses",
    "what is flex printing",
    "what is flute board printing",
    "how much does flex printing cost",
    "where to print flex banners",
    "best printing services near me",
    "how long do flex banners last",
    "what material is used for flex printing",
    "flex printing shop near me",
    "banner printing near my location",
    "where can I print flex banners",
    "best sign board maker near me",
    "printing shop open now near me"
  ],
  openGraph: {
    title: "Printing Services in Tanuku | Sri Teja Flex",
    description: "Complete range of printing and designing services in Tanuku, Andhra Pradesh. Flex printing, vinyl printing, LED sign boards, visiting cards and more.",
  },
}
